\set ON_ERROR_STOP on
BEGIN;
-- Remaining CONTROLLED TEST inquiry (self-marked [CONTROLLED TEST DATA][765 CONTROLLED INQUIRY])
DELETE FROM inquiry WHERE id='204b6570-8410-4e2d-9aec-88b08e2d7404'
  AND message LIKE '%CONTROLLED TEST DATA%';
COMMIT;
SELECT 'TEST_INQUIRY_PURGED' AS status;