import { createBrowserRouter, Navigate } from 'react-router-dom';
import { RequireAuth } from '../auth';
import AdminLayout from '../layouts/AdminLayout';
import { DemandDetail, DemandEdit, DemandList, EmbeddingManagement, FileAssetOrphanList, Home, Analytics, BusinessAnalytics, Monitoring, AuditIntelligence, InquiryDetail, InquiryList, Login, MatchDetail, MatchingMonitor, NotFound, NotificationDetail, NotificationList, OfferDetail, OfferList, OrganizationCreate, OrganizationDetail, OrganizationEdit, OrganizationList, ParameterDefinitionCreate, ParameterDefinitionDetail, ParameterDefinitionEdit, ParameterDefinitionList, ParameterGroupCreate, ParameterGroupDetail, ParameterGroupEdit, ParameterGroupList, ProductCategoryCreate, ProductCategoryEdit, ProductCategoryList, OperationCenter, ProductCreate, ProductDetail, ProductEdit, ProductList, ProductMediaCreate, ProductMediaEdit, ProductMediaList, RfqCreate, RfqDetail, RfqList, RfqResponseDetail, AuditLogList, UserCreate, UserDetail, UserEdit, UserList, ContentList, ContentCreate, ContentEdit, ContentTagList, ContentTagCreate, ContentTagEdit, KnowledgeDomainList, KnowledgeDomainCreate, KnowledgeDomainEdit, KnowledgeCategoryList, KnowledgeCategoryCreate, KnowledgeCategoryEdit, KnowledgeEntryList, KnowledgeEntryCreate, KnowledgeEntryEdit, MediaList, ProductCategoryKnowledgeMappingList, ProductCategoryKnowledgeMappingCreate, ProductCategoryKnowledgeMappingEdit, SupplierProductList, SupplierProductDetail } from '../pages';

const router = createBrowserRouter([
  {
    path: '/login',
    element: <Login />,
  },
  {
    path: '/',
    element: (
      <RequireAuth>
        <AdminLayout />
      </RequireAuth>
    ),
    children: [
      { index: true, element: <Navigate to="/home" replace /> },
      { path: 'home', element: <Home /> },
      { path: 'operation-center', element: <OperationCenter /> },
      { path: 'analytics', element: <Analytics /> },
      { path: 'business-analytics', element: <BusinessAnalytics /> },
      { path: 'monitoring', element: <Monitoring /> },
      { path: 'audit-intelligence', element: <AuditIntelligence /> },
      { path: 'products', element: <ProductList /> },
      { path: 'products/create', element: <ProductCreate /> },
      { path: 'products/:id/edit', element: <ProductEdit /> },
      { path: 'products/:id', element: <ProductDetail /> },
      { path: 'products/:productId/media', element: <ProductMediaList /> },
      { path: 'products/:productId/media/create', element: <ProductMediaCreate /> },
      { path: 'products/:productId/media/:id/edit', element: <ProductMediaEdit /> },
      { path: 'demands', element: <DemandList /> },
      { path: 'demands/:id', element: <DemandDetail /> },
      { path: 'demands/:id/edit', element: <DemandEdit /> },
      { path: 'demands/:demandId/matches/:matchId', element: <MatchDetail /> },
      { path: 'matching', element: <MatchingMonitor /> },
      { path: 'users', element: <UserList /> },
      { path: 'users/create', element: <UserCreate /> },
      { path: 'users/:id/edit', element: <UserEdit /> },
      { path: 'users/:id', element: <UserDetail /> },
      { path: 'organizations', element: <OrganizationList /> },
      { path: 'organizations/create', element: <OrganizationCreate /> },
      { path: 'organizations/:id/edit', element: <OrganizationEdit /> },
      { path: 'organizations/:id', element: <OrganizationDetail /> },
      { path: 'notifications', element: <NotificationList /> },
      { path: 'notifications/:id', element: <NotificationDetail /> },
      { path: 'rfqs/create', element: <RfqCreate /> },
      { path: 'rfqs', element: <RfqList /> },
      { path: 'rfqs/:id', element: <RfqDetail /> },
      { path: 'rfq-responses/:id', element: <RfqResponseDetail /> },
      { path: 'offers', element: <OfferList /> },
      { path: 'offers/:id', element: <OfferDetail /> },
      { path: 'supplier-products', element: <SupplierProductList /> },
      { path: 'supplier-products/:id', element: <SupplierProductDetail /> },
      { path: 'inquiries', element: <InquiryList /> },
      { path: 'inquiries/:id', element: <InquiryDetail /> },
      { path: 'parameter-groups', element: <ParameterGroupList /> },
      { path: 'parameter-groups/create', element: <ParameterGroupCreate /> },
      { path: 'parameter-groups/:id', element: <ParameterGroupDetail /> },
      { path: 'parameter-groups/:id/edit', element: <ParameterGroupEdit /> },
      { path: 'parameter-definitions', element: <ParameterDefinitionList /> },
      { path: 'parameter-definitions/create', element: <ParameterDefinitionCreate /> },
      { path: 'parameter-definitions/:id', element: <ParameterDefinitionDetail /> },
      { path: 'parameter-definitions/:id/edit', element: <ParameterDefinitionEdit /> },
      { path: 'product-categories', element: <ProductCategoryList /> },
      { path: 'product-categories/create', element: <ProductCategoryCreate /> },
      { path: 'product-categories/:id/edit', element: <ProductCategoryEdit /> },
      { path: 'files/orphans', element: <FileAssetOrphanList /> },
      { path: 'audit-logs', element: <AuditLogList /> },
      { path: 'content', element: <ContentList /> },
      { path: 'content/create', element: <ContentCreate /> },
      { path: 'content/:id', element: <ContentEdit /> },
      { path: 'content/tags', element: <ContentTagList /> },
      { path: 'content/tags/create', element: <ContentTagCreate /> },
      { path: 'content/tags/:id/edit', element: <ContentTagEdit /> },
      { path: 'embedding', element: <EmbeddingManagement /> },
      { path: 'knowledge/domains', element: <KnowledgeDomainList /> },
      { path: 'knowledge/domains/create', element: <KnowledgeDomainCreate /> },
      { path: 'knowledge/domains/:id/edit', element: <KnowledgeDomainEdit /> },
      { path: 'knowledge/categories', element: <KnowledgeCategoryList /> },
      { path: 'knowledge/categories/create', element: <KnowledgeCategoryCreate /> },
      { path: 'knowledge/categories/:id/edit', element: <KnowledgeCategoryEdit /> },
      { path: 'knowledge/entries', element: <KnowledgeEntryList /> },
      { path: 'knowledge/entries/create', element: <KnowledgeEntryCreate /> },
      { path: 'knowledge/entries/:id/edit', element: <KnowledgeEntryEdit /> },
      { path: 'media', element: <MediaList /> },
      { path: 'product-category-knowledge-mappings', element: <ProductCategoryKnowledgeMappingList /> },
      { path: 'product-category-knowledge-mappings/create', element: <ProductCategoryKnowledgeMappingCreate /> },
      { path: 'product-category-knowledge-mappings/:id/edit', element: <ProductCategoryKnowledgeMappingEdit /> },
    ],
  },
  {
    path: '*',
    element: <NotFound />,
  },
]);

export default router;