packages:
  - "apps/*"
  - "packages/*"
  - "database/*"
allowBuilds:
  '@prisma/client': false
  '@prisma/engines': false
  '@scarf/scarf': false
  bcrypt: true
  esbuild: true
  prisma: false
  sharp: false
  unrs-resolver: false
